# Generated by Django 5.1.4 on 2025-03-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
