# Generated by Django 5.1.4 on 2025-03-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_aulas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='subtitulo',
            field=models.CharField(default='Subtitulo', max_length=200),
        ),
    ]
