# Generated by Django 5.1.7 on 2025-03-21 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_aulas_subtitulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.CharField(max_length=1000)),
                ('alternativa_a', models.CharField(max_length=100)),
                ('alternativa_b', models.CharField(max_length=100)),
                ('alternativa_c', models.CharField(max_length=100)),
                ('alternativa_d', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alternativa_marcada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.questao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='simulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.simulado'),
        ),
    ]
