# Generated by Django 5.1.7 on 2025-03-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_questao_numero_questao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='alternativa_marcada',
        ),
        migrations.AddField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paginas.questao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='resposta',
            name='simulado_origem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paginas.simulado'),
        ),
    ]
