# Generated by Django 5.1.7 on 2025-03-27 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_remove_resposta_alternativa_marcada_resposta_questao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimuladoTeste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('duracao', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoSimulado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_questao', models.CharField(max_length=2)),
                ('enunciado', models.CharField(max_length=10000)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('id_simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='paginas.simulado')),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoSimuladoAlternativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correta', models.BooleanField(default=False)),
                ('texto', models.CharField(max_length=10000)),
                ('sla', models.CharField(default=1, max_length=1)),
                ('id_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='paginas.questaosimulado')),
            ],
        ),
        migrations.CreateModel(
            name='TextoSimulado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.CharField(max_length=100000)),
                ('referencia', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('id_simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='paginas.simulado')),
            ],
        ),
    ]
