# Generated by Django 5.1.7 on 2025-03-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_simuladoteste_questaosimulado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaosimulado',
            name='id_simulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='paginas.simuladoteste'),
        ),
        migrations.AlterField(
            model_name='textosimulado',
            name='id_simulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='paginas.simuladoteste'),
        ),
    ]
